---
-
  hosts: red
  remote_user: root
  become: yes

  tasks:
  - name: Installing Apache server
    yum: name=httpd state=latest

  - name: Downloading NodeSource repository
    get_url:
         url: https://rpm.nodesource.com/setup_14.x
         dest: /tmp/setup_14.x.sh

  - name: Remove file (delete file)
    ansible.builtin.file:
     path: /etc/yum.repos.d/nodesource-el8.repo
     state: absent

  - name: Adding NodeSource yum repository
    shell: /tmp/setup_14.x.sh | sudo bash -

  - name: Installing Node.js and npm
    yum:
      name:
        - nodejs
